# Generated by Django 3.1.5 on 2021-01-30 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('aluno_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('media', models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('prova_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('assunto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('questao_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('gabarito', models.CharField(choices=[('A', 'Letra A'), ('B', 'Letra B'), ('C', 'Letra C'), ('D', 'Letra D'), ('E', 'Letra E')], max_length=1)),
                ('peso', models.IntegerField()),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='app_alf.prova')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('resposta_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('resposta', models.CharField(choices=[('A', 'Letra A'), ('B', 'Letra B'), ('C', 'Letra C'), ('D', 'Letra D'), ('E', 'Letra E')], max_length=1)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='app_alf.aluno')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='app_alf.questao')),
            ],
        ),
        migrations.CreateModel(
            name='AlunosProva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=3)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='app_alf.aluno')),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='app_alf.prova')),
            ],
        ),
    ]
