# Generated by Django 3.1.5 on 2021-01-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunosprova',
            name='nota',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
